name: Update README

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - name: Check commit message
        uses: GsActions/commit-message-checker@v1
        with:
          pattern: '^(Add|Delete|Update) \d+\.\w+( \| (Add|Delete|Update) \d+\.\w+)*$'
          flags: 'gm'
          error: 'Commit message should start with Add or Delete or Update'
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Install Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Push to github
        run: |
          cd action
          npm install
          id=($(echo "${{ steps.files.outputs.all }}" | grep -oP '\d{4,}'))
          node main.js ${id[@]}
          git config --global user.name 'hackflakes'
          git config --global user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add ../README.md
          git add solved.json
          git commit -m "Update README.md"
          git push
